-- The iTunes fallback migration is applied by Store.migrateITunesFallback.
-- SQLite requires table rebuilds to widen the provider CHECK constraints while
-- preserving existing release observations and resolution rows.
